In [1]:
import tensorflow as tf
import numpy as np

In [4]:
x_vals = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

c_vals = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])

m_vals = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])

In [6]:
session = tf.Session()

In [7]:
x_data = tf.placeholder(tf.float32, shape=(3, 3))
c_data = tf.placeholder(tf.float32, shape=(3, 3))
m_data = tf.placeholder(tf.float32, shape=(3, 3))

In [8]:
y_data = tf.add(tf.multiply(m_data, x_data), c_data)

In [9]:
sess_result = session.run(y_data, feed_dict={m_data: m_vals, x_data: x_vals, c_data: c_vals})
print(sess_result)

[[ 2.  0.  0.]
 [ 0.  6.  0.]
 [ 0.  0. 10.]]
