In [4]:
import tensorflow as tf
import numpy as np
from tensorflow.python.framework import ops
ops.reset_default_graph()

In [5]:
session = tf.Session()

In [16]:
palceholder = tf.placeholder(tf.float32, shape=[5, 5])

y = tf.identity(palceholder)

print(session.run(y, feed_dict={palceholder: np.random.rand(5, 5)}))

[[0.04039098 0.92427844 0.7606509  0.9720829  0.62342715]
 [0.09605772 0.5951781  0.8655578  0.20076889 0.6939489 ]
 [0.54835254 0.89787906 0.8478224  0.21246284 0.7317443 ]
 [0.2799177  0.52950394 0.866879   0.7152216  0.88694257]
 [0.08323628 0.6861969  0.47797188 0.86954165 0.7673416 ]]


In [17]:
merger = tf.summary.merge_all()

In [18]:
writer = tf.summary.FileWriter("./logs/vars", session.graph)

## Matrix:

- Aheley samma thapako aanusar yo affai constant huncha, so initializer garrna parrdaina !!
 


In [20]:
mat_A = tf.fill([2,3], 5.0)
print(session.run(mat_A))

[[5. 5. 5.]
 [5. 5. 5.]]


In [26]:
numpy_array = np.random.rand(3, 3)
print("This is a numpy array {}".format(numpy_array))
tensor = tf.convert_to_tensor(numpy_array)

print("This is a tensor arey !! {} ".format(session.run(tensor)))

This is a numpy array [[0.65882839 0.90919824 0.52627116]
 [0.60526379 0.84891439 0.07121513]
 [0.20157051 0.94636524 0.65256484]]
This is a tensor arey !! [[0.65882839 0.90919824 0.52627116]
 [0.60526379 0.84891439 0.07121513]
 [0.20157051 0.94636524 0.65256484]] 
